name: Request Featured Status
description: Issue Template for getting your list featured.
title: "Featured Status Request [List Name]"
labels: ["Featured Request","in-progress"]
body:
  - type: markdown
    attributes:
      value: |
        This is the starting point for the process to get your list in the featured category. So please make sure that all the information you enter below is correct and that your list fits the quality standards.
  - type: dropdown
    id: game
    attributes:
      label: What game is your list for?
      description: Please 
      options:
        - "Baldur\u0027s Gate 3"
        - Cyberpunk 2077
        - Darkest Dungeon
        - Dishonored
        - "Dragon\u0027s Dogma: Dark Arisen"
        - Dragon Age 2
        - Dragon Age Inquisition
        - Enderal
        - Enderal Special Edition
        - Fallout 3
        - Fallout 4
        - Fallout 4 VR
        - Fallout New Vegas
        - Final Fantasy VII Remake Intergrade
        - "Karryn\u0027s Prison"
        - Kerbal Space Program
        - "Mount & Blade II: Bannerlord"
        - Sims 4
        - Stardew Valley
        - Terraria
        - TES Morrowind
        - TES Oblivion
        - TES Skyrim
        - TES Skyrim Special Edition
        - The Witcher
        - "The Witcher® 3: Wild Hunt"
        - "Kingdom Come: Deliverance"
        - "Mechwarrior 5: Mercenaries"
        - "No Man\u0027s Sky"
        - Other (please edit after posting)
    validations:
      required: true
  - type: input
    id: list_name
    attributes:
      label: What is your modlist called?
      description: Provide the name of your modlist.
      placeholder: My modlist
    validations:
      required: true
  - type: input
    id: support_server
    attributes:
      label: Where do you offer support for your modlist?
      description: Provide the link to the (Discord) support server for your modlist.
    validations:
      required: true
  - type: input
    id: readme
    attributes:
      label: Link to readme/documentation
      description: Please provide a link to your readme / user documentation.
    validations:
      required: true
  - type: textarea
    id: find_a_modlist
    attributes:
      label: Find A Modlist Assets and Meta Information
      description: |
        We use multiple things to promote lists to users who are unsure of which modlist to play. Please explain where your list will fit in the following:
        
        - https://github.com/wabbajack-tools/mod-lists/blob/master/modlist-descriptions.md
        - https://wizard.wabbajack.org/
        - https://www.figma.com/board/obqet5Mvte1C2l849BbBSq/Wabbajack-Skychart
        
        Additionally, please provide the following information:
        1 - Link to modlist thumbnail:
        2 - List name and author:
        3 - Find out more link:
        4 - Does the game require anything more than the base game? If yes, what does it require (any specific DLCs that are not included in the base game or in the case of Skyrim: the Anniversary Edition DLC?)
        5 - What differences does your modlist have to similiar lists? This information is meant for use in the 'find a modlist' quiz.
        5 - In the case of Skyrim: where do you think your list fits in the chart and wizard? Refer to the existing resources for an idea of what we are looking for.
    validations:
      required: true
  - type: input
    id: image
    attributes:
      label: Provide a WebP image for your modlist thumbnail for use in the "Find a List" tools and website promotion.
      description: "Ideally a 16:9 aspect ratio and a resolution of 1920x1080."
    validations:
      required: true
  - type: input
    id: lifetime
    attributes:
      label: When did you release the list on the Wabbajack UI?
      description: Your list is required to be available for 30 days before we can test it. This is required so we can compare and judge the existing support over time. 
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Agreements
      description: By submitting this request, you agree to the following.
      options:
        - label: "The work submitted in this request is my own, and in my branding and doesn't infringe on existing intellectual property or brands."
          required: true
        - label: "My list has custom patching as required to address any known conflicts, bugs, or crashes"
          required: true
        - label: I agree to fully open, honest and possibly critical examination and discussion of my here submitted work.
          required: true
